receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:

  # jaeger:
  #   endpoint: jaeger-all-in-one:14250
  #   insecure: true

  otlp/elastic: 
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: "192.168.0.103:8200"  
    insecure: true
    # headers:
      # Elastic APM Server secret token
      # Authorization: "Bearer ${ELASTIC_APM_SERVER_TOKEN}"  

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]
    metrics:
      receivers: [otlp]
      exporters: [otlp/elastic]
